/*
 * Copyright 2001-2008 Aqris Software AS. All rights reserved.
 * 
 * This program is dual-licensed under both the Common Development
 * and Distribution License ("CDDL") and the GNU General Public
 * License ("GPL"). You may elect to use one or the other of these
 * licenses.
 */
package net.sf.refactorit.refactorings.conflicts;

import net.sf.refactorit.classmodel.BinMethod;


public abstract class MethodInheritanceConflict extends
    ChangedFunctionalityConflict {
  /** Autogenerated proxy constructor. */
  public MethodInheritanceConflict(ConflictResolver resolver, BinMethod method) {
    super(resolver, method, null);

    this.method = method;
  }

  BinMethod method;

  public abstract String getDescription();

  public abstract ConflictType getType();
}
