
public abstract class B extends A {

  /** Autogenerated proxy constructor. */
  public B(String str) {
    super(str);
  }

  public abstract void method2();

  private boolean field = true;

  public void method() {/*override*/
  }

}
