/*
 * Copyright 2001-2008 Aqris Software AS. All rights reserved.
 * 
 * This program is dual-licensed under both the Common Development
 * and Distribution License ("CDDL") and the GNU General Public
 * License ("GPL"). You may elect to use one or the other of these
 * licenses.
 */
package net.sf.refactorit.refactorings.conflicts.resolution;

import net.sf.refactorit.classmodel.BinMethod;
import net.sf.refactorit.refactorings.conflicts.ConflictResolver;


public class OverridesMethodResolution extends MethodInheritanceResolution {
  /** Autogenerated proxy constructor. */
  public OverridesMethodResolution(final BinMethod method) {
    super(method);
  }

  public void runResolution(ConflictResolver resolver) {
    setIsResolved(true);
  }
}
