
public class B extends A {

  /** Autogenerated proxy constructor. */
  public B(String str) {
    super(str);
  }

  /** Autogenerated proxy constructor. */
  public B(String str, int i) {
    super(str, i);
  }

  private boolean field = true;

}
